# Generated by Django 4.1.1 on 2022-10-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='contrasenia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='contrasenia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario',
            field=models.CharField(max_length=10),
        ),
    ]
