# Generated by Django 4.1.1 on 2022-10-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0002_alter_cliente_nombre_alter_cuenta_contrasenia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fechaFin',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fechaInicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='monto',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='plataforma',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
