# Generated by Django 4.1.1 on 2022-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0003_perfil_fechafin_perfil_fechainicio_perfil_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='fechaAdquisicion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Adquisición'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='fechaCaducidad',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Caducidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=11, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cantPerfiles',
            field=models.IntegerField(verbose_name='Cantidad de Perfiles'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='contrasenia',
            field=models.CharField(max_length=10, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaFin',
            field=models.DateField(verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaInicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='modoPago',
            field=models.CharField(max_length=5, verbose_name='Modo de Pago'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='monto',
            field=models.FloatField(null=True, verbose_name='Monto [S/**.**]'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='contrasenia',
            field=models.CharField(max_length=10, verbose_name='Contraseña'),
        ),
    ]
