# Generated by Django 4.1.1 on 2022-10-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0004_cuenta_fechaadquisicion_cuenta_fechacaducidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fechaAdquisicion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Adquisición [DD-MM-AAAA]'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaCaducidad',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Caducidad [DD-MM-AAAA]'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaFin',
            field=models.DateField(verbose_name='Fecha de Fin [DD-MM-AAAA]'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaInicio',
            field=models.DateField(verbose_name='Fecha de Inicio [DD-MM-AAAA]'),
        ),
    ]
