# Generated by Django 4.1.1 on 2022-10-24 05:50

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0005_alter_cuenta_fechaadquisicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='vendedor',
            field=models.CharField(max_length=5, null=True, verbose_name='Vendedor'),
        ),
    ]
