# Generated by Django 4.1.1 on 2022-10-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0008_perfil_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='vendedor',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Vendedor'),
        ),
    ]
