# Generated by Django 4.1.1 on 2022-10-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0009_alter_perfil_vendedor'),
    ]

    operations = [
    ]
