# Generated by Django 4.1.1 on 2022-10-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0010_merge_20221024_0111'),
    ]

    operations = [
    ]
