# Generated by Django 4.1.1 on 2022-10-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0011_merge_20221024_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='vendedor',
        ),
    ]
