# Generated by Django 4.1.1 on 2022-10-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0013_alter_cliente_nombre_alter_cliente_telefono'),
    ]

    operations = [
    #    migrations.AddField(
    #        model_name='vendedor',
     #       name='idAdmin',
    #        field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código de admin'),
    #    ),
        migrations.AddField(
            model_name='vendedor',
            name='telefono',
            field=models.CharField(default='999 999 999', max_length=11, unique=True, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='correo',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario',
            field=models.CharField(max_length=10, verbose_name='Nombre'),
        ),
    ]
