# Generated by Django 4.1.1 on 2022-10-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0014_vendedor_idadmin_vendedor_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='usuario',
            new_name='nombre',
        ),
    ]
