# Generated by Django 4.1.1 on 2022-10-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0015_rename_usuario_vendedor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='contrasenia',
            field=models.CharField(max_length=10, unique=True, verbose_name='Contraseña'),
        ),
    ]
