# Generated by Django 4.1.1 on 2022-10-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0016_alter_vendedor_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cantPerfiles',
            field=models.IntegerField(verbose_name='Cantidad máxima de Perfiles'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='correo',
            field=models.EmailField(max_length=30, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaAdquisicion',
            field=models.DateField(verbose_name='Fecha de Adquisición [DD-MM-AAAA]'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaCaducidad',
            field=models.DateField(verbose_name='Fecha de Caducidad [DD-MM-AAAA]'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='plataforma',
            field=models.CharField(max_length=10, verbose_name='Plataforma'),
        ),
    ]
