# Generated by Django 4.1.1 on 2022-10-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0017_alter_cuenta_cantperfiles_alter_cuenta_correo_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='vendedor',
        #    name='idAdmin',
        #),
        migrations.AddField(
            model_name='cuenta',
            name='admin',
            field=models.IntegerField(null=True, verbose_name='Registrado por Admin'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('idVendedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gestionVenta.vendedor', verbose_name='Id Vendedor')),
            ],
        ),
    ]
