# Generated by Django 4.1.1 on 2022-10-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0018_remove_vendedor_idadmin_cuenta_admin_administrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='admin',
            new_name='idVendedor',
        ),
    ]
