# Generated by Django 4.1.1 on 2022-10-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0019_rename_admin_cuenta_idvendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='idVendedor',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idAdmin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionVenta.administrador', verbose_name='Registrado por Admin'),
        ),
    ]
