# Generated by Django 4.1.1 on 2022-10-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0020_remove_cuenta_idvendedor_cuenta_idadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionVenta.cliente', verbose_name='Id de Cliente'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='idCuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionVenta.cuenta', verbose_name='Id de Cuenta'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='idVendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionVenta.vendedor', verbose_name='Vendedor'),
        ),
    ]
