# Generated by Django 4.1.1 on 2022-10-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0021_perfil_idcliente_perfil_idcuenta_perfil_idvendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombrePerfil',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre del Perfil'),
        ),
    ]
