# Generated by Django 4.1.1 on 2022-10-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0022_remove_perfil_perfil_remove_perfil_plataforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='idCuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionVenta.cuenta', verbose_name='Cuenta'),
        ),
    ]
